Add cgroup package and tests
bill-rich/rjob pull request #1
Opened 2021-11-12 20:23 UTC by bill-rich

The cgroup package manages mounting and unmounting the cgroup hierarchy, creating and deleting cgroups, and managing the CPU, memory, and IO limits for a cgroup.

2021-11-12 23:38 UTC, zmb3 requested changes
This cgroup stuff can get pretty repetitive, so I left a few suggestions for refactors to try and get rid of some of the duplicated code.

I also think we could improve the tests by:

1. Using table tests where appropriate, and
2. Where table tests are not appropriate, putting the logic in proper Go test functions (`TestSomeThing(t *testing.T)`). The way you have it now with a bunch of separate unexported test methods makes it a little hard to tell what functionality you're actually trying to test.

2021-11-12 23:38 UTC, zmb3 commented on Makefile
> +test: test_unit test_integration
Should probably mark these targets `PHONY`.

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup.go
> +		return fmt.Errorf("error mounting cgroup2 at %s: %s", mountDir, err)
Should you delete the directory you created at `mountDir` if this fails?

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup.go
> +	cpuFile, err := os.OpenFile(fmt.Sprintf("%s/cpu.max", cg.Path), os.O_APPEND|os.O_WRONLY, fileMode)
`filepath.Join` is probably a better tool for building file paths than `Sprintf`.

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup.go
> +func (cg *CgroupConfig) setBlkIoLimit() error {
`setCpuLimit`, `setMemoryLimit` and `setBlkIoLimit` are almost identical. They open a file, write a string to it, and close the file.

Any opportunities for a refactor here?

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup.go
> +	case cg.Cpu < 1:
I'd almost prefer getting an error if the input is invalid rather than doing something different than what the user requested.

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup_integration_test.go
> +func testCgroupMounted(path string) (bool, error) {
My expectation would be that something named `test*` in a `_test.go` file is going to make assertions. This is less of a test and more of a helper method. With that in mind, would this be a better name?

```suggestion
func isCgroupMounted(path string) (bool, error) {
```

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup_integration_test.go
> +		t.Error(err)
In `testMount` these are fatal test failures, but here they're only errors. Any particular reason for the discrepancy?

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup_integration_test.go
> +	if err := Mount(CgroupMountDir); err != nil {
I would consider calling `t.Helper()` in these helpers that you run from multiple tests. It can be easier to identify where the failure was when there's many possible code paths into `testMount`.

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup_integration_test.go
> +func (config *CgroupConfig) testVerifyCgroupSettings(t *testing.T) {
What exactly is going on here? I'm a little confused.

1. It seems odd to me to define new methods on a type only in a test file.
2. Is there even a need for this method at all? It only does one thing. If you plan to add further checks for other (non-CPU) settings, I would add a TODO so you don't forget.

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup_integration_test.go
> +	if strings.Compare(strings.TrimSuffix(string(cpuData), "\n"), config.getCpuMax()) != 0 {
In general, if you have a `[]byte` you should prefer `bytes.Compare`, `bytes.TrimSuffix`, etc.

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup_integration_test.go
> +func (config *CgroupConfig) testVerifyCgroupIoSetting(t *testing.T) {
Similar to a previous comment, most of these methods look exactly the same.

In this case, I would refactor and use a [table driven test](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests) to check the different cgroup settings.

2021-11-12 23:38 UTC, zmb3 commented on lib/cgroup/cgroup_test.go
> +func TestGetCpuMaxUnderMin(t *testing.T) {
Same thing here, rather than a bunch of separate CPU max tests, just build a little table with your inputs and expected outputs.

2021-11-13 22:14 UTC, bill-rich commented on Makefile
> +test: test_unit test_integration
Good call!

2021-11-13 22:15 UTC, bill-rich commented on lib/cgroup/cgroup.go
> +		return fmt.Errorf("error mounting cgroup2 at %s: %s", mountDir, err)
Yes. It would be better to get the system back into the same state it started in.

2021-11-13 22:16 UTC, bill-rich commented on lib/cgroup/cgroup.go
> +	cpuFile, err := os.OpenFile(fmt.Sprintf("%s/cpu.max", cg.Path), os.O_APPEND|os.O_WRONLY, fileMode)
It definitely would. I got on a kick of using `Sprintf`.

2021-11-13 22:25 UTC, bill-rich commented on lib/cgroup/cgroup.go
> +func (cg *CgroupConfig) setBlkIoLimit() error {
There certainly are. I originally had the logic for getting the CPU, memory, and IO values in these functions, but didn't think to combine them when I split those out.

2021-11-14 22:15 UTC, bill-rich commented on lib/cgroup/cgroup_test.go
> +func TestGetCpuMaxUnderMin(t *testing.T) {
Definitely a better way to go. Much easier to parse what is going on using a table of tests for each.

2021-11-14 22:49 UTC, bill-rich commented on lib/cgroup/cgroup_integration_test.go
> +	if strings.Compare(strings.TrimSuffix(string(cpuData), "\n"), config.getCpuMax()) != 0 {
Totally agree. Thanks!

2021-11-14 22:50 UTC, bill-rich commented on lib/cgroup/cgroup_integration_test.go
> +func (config *CgroupConfig) testVerifyCgroupSettings(t *testing.T) {
This was supposed to be a function that runs checks for CPU, memory, and IO, but I forgot to add the memory and IO part.

2021-11-14 22:51 UTC, bill-rich commented on lib/cgroup/cgroup_integration_test.go
> +	if err := Mount(CgroupMountDir); err != nil {
Good call. Figuring out where things went wrong is much more clear with the helpers marked.

2021-11-14 22:55 UTC, bill-rich commented on lib/cgroup/cgroup_integration_test.go
> +		t.Error(err)
The thought was that stopping when mounting fails would keep any further setup from being done, but when there's a failure in unmounting, it may still be beneficial to keep trying to clean up.

2021-11-14 23:01 UTC, bill-rich commented on lib/cgroup/cgroup_integration_test.go
> +func testCgroupMounted(path string) (bool, error) {
It's definitely more of a helper method. I've generally kept all helpers starting with `test` just to make it clear it is a test helper rather than something that may be used somewhere else. That being said, I see what you mean about no assertion being made. I'd probably prefer something like `testIsCgroupMounted`, but that is just my preference. I'm happy to go along with whatever convention is in use.

2021-11-14 23:02 UTC, bill-rich commented on lib/cgroup/cgroup.go
> +	case cg.Cpu < 1:
Agreed. Especially because I'm planning on validating the cgroup limits before putting them into a config. If they are outside of the expected range, something has gone wrong.

2021-11-14 23:04 UTC, bill-rich commented on lib/cgroup/cgroup_integration_test.go
> +func (config *CgroupConfig) testVerifyCgroupSettings(t *testing.T) {
Also, agreed on the methods. There isn't any benefit here to making these methods over using functions that accept the `CgroupConfig`.

2021-11-14 23:09 UTC, bill-rich commented on lib/cgroup/cgroup_integration_test.go
> +func (config *CgroupConfig) testVerifyCgroupIoSetting(t *testing.T) {
I did some refactoring to get rid of the overlap. I didn't switch over to doing a table-driven test here because the number of checks being done is still fairly small, and I thought that keeping it this way makes it a little easier to parse what is going on at first glance.

2021-11-15 09:50 UTC, merged

2021-11-15 14:53 UTC, zmb3 commented on lib/cgroup/cgroup_integration_test.go
> +func testCgroupMounted(path string) (bool, error) {
`testIsCgroupMounted` is fine, but I would have passed in `t` and make assertions there, just like you've already done for `testMount`, `testUnmount`, `testVerifyCgroupSettings`, etc.


Also, w.r.t 
> just to make it clear it is a test helper rather than something that may be used somewhere else

The fact that the function is unexported and lives in an _test.go file is probably a pretty good signal that it's not used somewhere else.